SELECT COUNT(*) FROM mock_data;
drop table sales;
Drop TABLE dm_customer  ;
Drop TABLE dm_products ;
Drop TABLE dm_sellers  ;
Drop TABLE dm_stores  ;
drop table dm_supplier ;
drop table dm_country;
drop table dm_city;
drop table dm_pet;
drop table dm_kind;
drop table dm_breed;
drop table dm_pet_category;
drop table dm_product_brand ;
drop table dm_product_category ;
drop table dm_product_color ;
drop table dm_product_material  ;
drop table d_time;
drop table d_day;
drop table d_month;